def probe_version() -> str: ...

class ResourceSnapshot:
    rss_bytes: int
    vms_bytes: int
    open_fds: int
    timestamp_ns: int
    def rss_mb(self) -> float: ...
    def vms_mb(self) -> float: ...
    def __repr__(self) -> str: ...

def snapshot_resources() -> ResourceSnapshot: ...
def list_open_fds() -> list[str]: ...